; Script generated by Inno Setup for Dacreator-GUI
; Version 2.1.2
; Developer: TakahashiRinta

[Setup]
AppId={{DACREATOR-GUI} 
AppName=Dacreator-GUI
AppVersion=2.1.2
AppPublisher=TakahashiRinta
AppPublisherURL=https://github.com/TakahashiRinta
AppSupportURL=https://github.com/TakahashiRinta/Dacreator-GUI
AppUpdatesURL=https://github.com/TakahashiRinta/Dacreator-GUI/releases
DefaultDirName={pf}\Dacreator-GUI
DefaultGroupName=Dacreator-GUI
AllowNoIcons=yes
LicenseFile=LICENSE
OutputDir=.
OutputBaseFilename=Dacreator-GUI-Setup-2.1.2
Compression=lzma2/ultra
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; 递归添加所有文件，排除 .git 目录及其内容
Source: "*"; DestDir: "{app}"; Flags: recursesubdirs; Excludes: ".git\*,.git"

[Icons]
; 开始菜单快捷方式
Name: "{group}\Dacreator-GUI"; Filename: "{app}\run_gui.bat"; IconFilename: "{app}\run_gui.bat"; WorkingDir: "{app}"
; 桌面快捷方式
Name: "{commondesktop}\Dacreator-GUI"; Filename: "{app}\run_gui.bat"; IconFilename: "{app}\run_gui.bat"; WorkingDir: "{app}"

[Run]
; 安装完成后运行主程序（可选，用户可选择）
Filename: "{app}\run_gui.bat"; Description: "启动 Dacreator-GUI"; Flags: postinstall nowait skipifsilent